# Generated by Django 6.0.3 on 2026-04-11 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyhealthlogs',
            name='screen_time_hours',
        ),
        migrations.AddField(
            model_name='dailyhealthlogs',
            name='screen_time',
            field=models.FloatField(default=datetime.date(2026, 4, 11)),
            preserve_default=False,
        ),
    ]
