# Generated by Django 6.0.3 on 2026-04-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_remove_dailyhealthlogs_screen_time_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyhealthlogs',
            name='screen_time',
        ),
        migrations.AddField(
            model_name='dailyhealthlogs',
            name='screen_time_hours',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyhealthlogs',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
